### ISSUE TITLE
Relaton XML in DB have funny names

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/tc211-termbase#7]
The names should only include the document identifier, not the modification or clause ID.

e.g.

<img width="465" alt="Screen Shot 2019-07-04 at 7 05 59 PM" src="https://user-images.githubusercontent.com/11865/60662404-df469400-9e8e-11e9-91d8-04401b7a4974.png">

<img width="915" alt="Screen Shot 2019-07-04 at 7 06 55 PM" src="https://user-images.githubusercontent.com/11865/60662413-e53c7500-9e8e-11e9-8b2e-e869f0843d0e.png">

**Comment by andrew2net** [comment]
@ronaldtse obviously it's the `relaton` gem's issue. I'll check it later.

**Comment by andrew2net** [comment]
@ronaldtse it is not `relaton` gem's issue. We need to clean reference form modification or clause ID before fetch document.
There is also another problem. Some `authoritative_source` contains incorrect references. For example with a semicolon instead of a colon, or with a not standard hyphen:
- ISO 10303‑227:2005 has a not standard hyphen
- ISO 19108;2002 has semicolon instead colon
So `relaton` returns `not_found` for these refs. I'll add code to correct such a references. Plese let me know if you find more type of typos.

**Comment by ronaldtse** [comment]
@andrew2net Got it. We should "clean" them in the tc211-termbase gem during parsing. Can you help do that?

I will work with TC 211 to clean the source.

**Comment by andrew2net** [comment]
>  Got it. We should "clean" them in the tc211-termbase gem during parsing. Can you help do that?

@ronaldtse Yes, I'm working o it already.
Also, I've discovered relaton-iso doesn't fetch corrections like Amd. So it needs to update relaton-iso.

**Comment by ronaldtse** [comment]
@andrew2net you're right. We should handle the document types like Cor and Amd.
